from src.utils import *

DEBUG = True

class SebaInputArguments:
    s_help = f"-h"
    l_help = f"--help"
    m_help = f"{s_help}, {l_help}\t\t\tShow this message"

    s_setup = f"-s"
    l_setup = f"--setup"
    m_setup = f"{s_setup}, {l_setup} <repo_path>\t\tSetup repository with provided <repo_path>"

    l_setup_force = f"--setup_force"
    m_setup_force = f"  , {l_setup_force} <repo_path>\tForcing setup of reposiotory with provided <repo_path>"\
                     "exisitng path will be removed"
    
    s_debug = f"-d"
    l_debug = f"--debug"
    m_debug = f"{s_setup}, {l_debug} \t\t\t Showing debug info"


class SebaDirectoryTemplate:
    gitignore_file_content =    "# Default SEBA .gitignore file\n\n"\
                                "tmp/\n"\
                                "logs/\n"\
                                "backup/\n"\
                                "pex/\n"

    seba_config_file_content =  "# Example of configuration for SEBA file\n"\
                                "NAME           <TB_NAME>           # Name of testbench, temporary files will be placed in tmp/simulations\n"\
                                "                                   # report will be created under this name\n"\
                                "CONTROL        <control.spice>     # Control file that will be inserted into final SPICE file\n"\
                                "TESTBENCH      <testbench.sch>     # xschem schematic of testbench that will be inserted as netlist into final SPICE file\n"\
                                "CORNERS        <corner.gen>        # Corner generation file\n"\
                                "SCRIPT         <script.py>         # Script for measurment generation\n"\
                                "PLOT           <plot.plt>          # Plot file for report generation,\n"\
                                "                                   # measurment generated by script will be merged with specification defined by plot flie\n"\
                                "[EXTRACTION]   <layout.pex.spice>  # Optional argument for post-layout simulation, this file will be replace subckt, with corresponding name, in final SPICE file"
    
    corner_gen_file_content =   "# Example for corner generation file\n"\
                                "lib    cornerMOSlv.lib\n"\
                                "lib    cornerMOShv.lib\n"\
                                "param  xvp\n"\
                                "param  xtemp\n"\
                                "param  xvbg\n"\
                                "param  xfreq\n"\
                                "#          ! DONT USE SPACES INSIDE BRACKETS !\n"\
                                "corner_gen [mos_tt]==[mos_tt] [3.3] [25] [0.8] [100e6]\n"\
                                "corner_gen [mos_ss,mos_sf,mos_fs,mos_ff]==[mos_ss,mos_sf,mos_fs,mos_ff] [2.97,3.6] [-50,125] [0.79,0.81] [100e6]\n"\
                                "corner_gen [mos_tt]==[mos_tt] [3.3] [25] [0.8] [200e6]\n"\
                                "corner_gen [mos_ss,mos_sf,mos_fs,mos_ff]==[mos_ss,mos_sf,mos_fs,mos_ff] [2.97,3.6] [-50,125] [0.79,0.81] [200e6]\n"\
    
    plot_file_content =         "# Example for plot file\n"\
                                "# meas_name    |   min_spec    |   max_spec    |   unit    |   prefix  |   description\n"\
                                "vout               400             800             V           m           \"Output voltage\"\n"\
                                "iout               75              125             A           u           \"Output current\"\n"\
                                "duty_cycle         0.45            0.55            ratio       None        \"Output duty cycle\""\
    
    if DEBUG == True:
        debug_xschem_file = DefaultFile("xschem.debug.sch", "<xschem file content>")
        debug_pex_file = DefaultFile("circuit.pex.spice", "<pex sub circuit>")
        seba_config_file = DefaultFile("config.template.seba", seba_config_file_content)
        gitignore_file = DefaultFile(".gitignore", gitignore_file_content)
        corner_gen_file = DefaultFile("croner.template.gen", corner_gen_file_content)
        plot_file = DefaultFile("plot.template.plt", plot_file_content)
        seba_folder = FolderTree("seba", [seba_config_file])
        spfiles_folder = FolderTree("control", ["<control.spice>"])
        tb_folder = FolderTree("tb", ["<testbench.sch>"])
        circuit_folder = FolderTree("circuit", ["<circuit.sch>", "<circuit.sym>"])
        layout_folder = FolderTree("layout", ["<layout.gds>"])
        corners_folder = FolderTree("corners", [corner_gen_file, "<corner.gen>", "<corner.list>"])
        pex_folder = FolderTree("pex", ["<circuit.pex.spice>"])
        scripts_folder = FolderTree("scripts", ["<script.py>"])
        plot_folder = FolderTree("plot", [plot_file, "<plot.plt>"])
        reports_folder = FolderTree("reports", ["<index.html>"])
        logs_folder = FolderTree("logs", ["<seba.log>"])
        simulations_folder = FolderTree("simulations", ["sim_1_tb", "...", "sim_n_tb"])
        layout_flatten_gds_folder = FolderTree("layout_flatten_gds", [])
        layout_lvs_folder = FolderTree("layout_lvs", [])
        layout_drc_folder = FolderTree("layout_drc", [])
        pex_tmp_folder = FolderTree("pex_tmp", [])
        tmp_folder = FolderTree("tmp", [simulations_folder, layout_flatten_gds_folder, layout_lvs_folder, layout_drc_folder, pex_tmp_folder])
        backup_folder = FolderTree("backup", ["<backup.zip>"])
        root_tree = FolderTree("<repo_name>", [seba_folder, spfiles_folder, tb_folder, circuit_folder,
                                            layout_folder, corners_folder, pex_folder, scripts_folder,
                                            plot_folder, reports_folder, logs_folder, tmp_folder,
                                            backup_folder, gitignore_file])
    
    else:        
        seba_config_file = DefaultFile("config.template.seba", seba_config_file_content)
        gitignore_file = DefaultFile(".gitignore", gitignore_file_content)
        corner_gen_file = DefaultFile("croner.template.gen", corner_gen_file_content)
        plot_file = DefaultFile("plot.template.plt", plot_file_content)
        seba_folder = FolderTree("seba", [seba_config_file])
        spfiles_folder = FolderTree("control", ["<control.spice>"])
        tb_folder = FolderTree("tb", ["<testbench.sch>"])
        circuit_folder = FolderTree("circuit", ["<circuit.sch>", "<circuit.sym>"])
        layout_folder = FolderTree("layout", ["<layout.gds>"])
        corners_folder = FolderTree("corners", [corner_gen_file, "<corner.gen>", "<corner.list>"])
        pex_folder = FolderTree("pex", ["<circuit.pex.spice>"])
        scripts_folder = FolderTree("scripts", ["<script.py>"])
        plot_folder = FolderTree("plot", [plot_file, "<plot.plt>"])
        reports_folder = FolderTree("reports", ["<index.html>"])
        logs_folder = FolderTree("logs", ["<seba.log>"])
        simulations_folder = FolderTree("simulations", ["sim_1_tb", "...", "sim_n_tb"])
        layout_flatten_gds_folder = FolderTree("layout_flatten_gds", [])
        layout_lvs_folder = FolderTree("layout_lvs", [])
        layout_drc_folder = FolderTree("layout_drc", [])
        pex_tmp_folder = FolderTree("pex_tmp", [])
        tmp_folder = FolderTree("tmp", [simulations_folder, layout_flatten_gds_folder, layout_lvs_folder, layout_drc_folder, pex_tmp_folder])
        backup_folder = FolderTree("backup", ["<backup.zip>"])
        root_tree = FolderTree("<repo_name>", [seba_folder, spfiles_folder, tb_folder, circuit_folder,
                                            layout_folder, corners_folder, pex_folder, scripts_folder,
                                            plot_folder, reports_folder, logs_folder, tmp_folder,
                                            backup_folder, gitignore_file])
