from src.utils import *

class SebaDirectoryTemplate:
    ### TODO: Add default dummy xschem file for debug purpose

    seba_config_file_content =  "# Example of configuration for SEBA file\n"\
                                "NAME           <TB_NAME>           # Name of testbench, temporary files will be placed in tmp/simulations\n"\
                                "                                   # report will be created under this name\n"\
                                "CONTROL        <control.spice>     # Control file that will be inserted into final SPICE file\n"\
                                "TESTBENCH      <testbench.sch>     # xschem schematic of testbench that will be inserted as netlist into final SPICE file\n"\
                                "CORNERS        <corner.gen>        # Corner generation file\n"\
                                "SCRIPT         <script.py>         # Script for measurment and plot generation\n"\
                                "MEAS           <measurment.meas>   # Measurment file for report generation,\n"\
                                "                                   # measurment generated by script will be merged with specification defined by measurment flie\n"\
                                "PLOT           <plot.plt>          # Plot file for report genration\n"\
                                "                                   # plots generated by script will be merged with plot defined in plot file\n"\
                                "EXTRACTION   <layout.pex.spice>    # Optional argument for post-layout simulation, this file will be replace subckt, with corresponding name, in final SPICE file\n"
    
    corner_gen_file_content =   "# Example for corner generation file\n"\
                                "lib    cornerMOSlv.lib\n"\
                                "lib    cornerMOShv.lib\n"\
                                "param  xvp\n"\
                                "param  xtemp\n"\
                                "param  xvbg\n"\
                                "param  xfreq\n"\
                                "#          ! DONT USE SPACES INSIDE BRACKETS !\n"\
                                "corner_gen [mos_tt]==[mos_tt] [3.3] [25] [0.8] [100e6]\n"\
                                "corner_gen [mos_ss,mos_sf,mos_fs,mos_ff]==[mos_ss,mos_sf,mos_fs,mos_ff] [2.97,3.6] [-50,125] [0.79,0.81] [100e6]\n"\
                                "corner_gen [mos_tt]==[mos_tt] [3.3] [25] [0.8] [200e6]\n"\
                                "corner_gen [mos_ss,mos_sf,mos_fs,mos_ff]==[mos_ss,mos_sf,mos_fs,mos_ff] [2.97,3.6] [-50,125] [0.79,0.81] [200e6]\n"\
    
    meas_file_content =         "# Example for meas file\n"\
                                "# meas_name    |   min_spec    |   max_spec    |   unit    |   prefix  |   description\n"\
                                "vout               400             800             V           m           \"Output voltage\"\n"\
                                "iout               75              125             A           u           \"Output current\"\n"\
                                "duty_cycle         0.45            0.55            ratio       None        \"Output duty cycle\"\n"\
    
    plot_file_content =         "# Example of plot file\n"\
                                "\n"

    seba_repo_file = DefaultFile(".seba", "")
    seba_config_file = DefaultFile("config.template.seba", seba_config_file_content)
    corner_gen_file = DefaultFile("croner.template.gen", corner_gen_file_content)
    corner_list_file = TemporaryFile("<corner.list>", "", pattern="*.list")
    seba_log_file = TemporaryFile("<seba.log>", "", pattern="*.log")
    seba_log_folder = TemporaryFolder("logs", [seba_log_file])
    meas_file = DefaultFile("meas.template.plt", meas_file_content)
    plot_file = DefaultFile("plot.template.file", plot_file_content)
    seba_folder = Folder("seba", [seba_config_file, seba_log_folder])
    spfiles_folder = Folder("control", ["<control.spice>"])
    tb_folder = Folder("tb", ["<testbench.sch>"])
    circuit_folder = Folder("circuit", ["<circuit.sch>", "<circuit.sym>"])
    layout_folder = Folder("layout", ["<layout.gds>"])
    corners_folder = Folder("corners", [corner_gen_file, "<corner.gen>", corner_list_file])
    pex_folder = TemporaryFolder("pex", ["<circuit.pex.spice>"])
    scripts_folder = Folder("scripts", ["<script.py>"])
    result_gen_folder = Folder("result_gen", [meas_file, "<meas.meas>", plot_file, "<plot.plt>",])
    reports_folder = Folder("reports", ["<index.html>"])
    logs_folder = TemporaryFolder("logs", ["<seba.log>"])
    simulations_folder = TemporaryFolder("simulations", ["sim_1_tb", "...", "sim_n_tb"])
    layout_flatten_gds_folder = TemporaryFolder("layout_flatten_gds", [])
    layout_lvs_folder = TemporaryFolder("layout_lvs", [])
    layout_drc_folder = TemporaryFolder("layout_drc", [])
    pex_tmp_folder = TemporaryFolder("pex_tmp", [])
    tmp_folder = TemporaryFolder("tmp", [simulations_folder, layout_flatten_gds_folder, layout_lvs_folder, layout_drc_folder, pex_tmp_folder])
    backup_folder = TemporaryFolder("backup", ["<backup.zip>"])
    root_tree = Folder("<repo_name>", [seba_repo_file, seba_folder, spfiles_folder, tb_folder, circuit_folder,
                                            layout_folder, corners_folder, pex_folder, scripts_folder,
                                            result_gen_folder, reports_folder, logs_folder, tmp_folder,
                                            backup_folder])
    
    gitignore_file_content = "".join(gfc.replace("<repo_name>/", "")+"\n" for gfc in root_tree.generate_gitignore(header="# Default SEBA .gitignore file\n").split("\n"))
    gitignore_file = DefaultFile(".gitignore", gitignore_file_content)
    root_tree.insert_branch(gitignore_file)
    
